[mypy]
python_version = 3.13
strict = True

[mypy-ctranslate2]
ignore_missing_imports = True

[mypy-faster_whisper]
ignore_missing_imports = True

[mypy-sounddevice]
ignore_missing_imports = True

[mypy-pynput]
ignore_missing_imports = True

[mypy-pynput.*]
ignore_missing_imports = True

[mypy-pynput.keyboard]
ignore_missing_imports = True
